version: '3.8'
services:
  backend:
    build: .
    container_name: mediaflow-backend
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TZ=UTC
    restart: unless-stopped
